version: "3.8"

services:
  chrome:
    image: selenium/node-chrome:4.10.0-20230607
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HUB_PORT=4444
      - SE_NODE_MAX_CONCURRENT_SESSIONS=5
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
      - START_XVFB=false

  selenium-proxy:
    build:
      context: .
      dockerfile: ./compose/selenium-proxy/Dockerfile
    volumes:
      - .:/code

  selenium-hub:
    image: selenium/hub:4.10.0-20230607
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

